# Generated by Django 4.2.7 on 2023-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
