# Generated by Django 4.2.7 on 2023-12-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContryData',
            new_name='CountryData',
        ),
    ]
