# Generated by Django 5.0 on 2023-12-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('CountryName', models.CharField(max_length=255, verbose_name='Country Name')),
                ('CountryCode', models.CharField(max_length=255, verbose_name='Country Code')),
                ('Year_2022', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CountryData',
            new_name='Add_Data',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
