# Generated by Django 5.0 on 2023-12-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_upload_file_rename_countrydata_add_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='CountryCode',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='CountryName',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='Year_2022',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='upload_file',
            name='attributeid1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='attributeid2',
            field=models.BigIntegerField(default=0),
        ),
    ]
