# Generated by Django 5.0 on 2023-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_upload_file_countrycode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='attributeid1',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='attributeid2',
        ),
        migrations.AddField(
            model_name='upload_file',
            name='attribute1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='attribute2',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
